description: patch reco

environment:
  image: jinchaolove/dl:msra-torch1.12-conda3-cuda11.6-cudnn8-ubuntu20.04 
  setup:
    - pip install --user datasets evaluate 
    - export OUTPUT_DIR="/blob/v-yanpeng/others/lza/result/"
    - export CHECKPOINT_DIR="/blob/v-yanpeng/others/lza/checkpoints/"

target:
  name: msroctovc

code:
  local_dir: $CONFIG_DIR/../

storage:
  output:
      storage_account_name: msralaphilly2
      container_name: ml-la
      mount_dir: /blob

jobs:
  - name:  patch_reco_all 
    sku: 1x16G1-V100 
    command:
      - bash train.sh