description: patch reco

environment:
  image: jinchaolove/dl:msra-torch1.12-conda3-cuda11.6-cudnn8-ubuntu20.04 
  setup:
    - export OUTPUT_DIR='/blob/v-yanpeng/others/lza/'
    - pip install datasets evaluate 

target:
  name: msroctovc

code:
  local_dir: $CONFIG_DIR/../

storage:
  output:
      storage_account_name: msralaphilly2
      container_name: ml-la
      mount_dir: /blob

jobs:
  - name:  patch_reco 
    sku: 1x16G1-V100 
    command:
      - python main.py msg
      - python main.py code